spring:
  application:
    name: post-service
  
  profiles:
    active: dev
  
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  config:
    import:
      - classpath:api.properties

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.andev.post.web.endpoints
  paths-to-match: /api/v1/**

